name: clean_flutter_tdd_ddd
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.6.7
  # Bloc for state management
  flutter_bloc: ^8.1.4
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Checker for internet connection
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.1
  # Local cache
  shared_preferences: ^2.2.2
  flutter_redux: ^0.10.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8


flutter:
  uses-material-design: true